In [4]:
import numpy as np
import pandas as pd
boston_data=pd.read_csv("Datasets/train.csv")
boston_data

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494,50.0
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991,14.3
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043,20.8
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752,22.6
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713,50.0

In [6]:
x_train_boston_data = boston_data.iloc[:,0:13]
x_train_boston_data

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713

In [9]:
y_train_boston_data= boston_data.iloc[:,1]
y_train_boston_data

0     -0.487722
1     -0.487722
2     -0.487722
3     -0.487722
4     -0.487722
         ...
374   -0.487722
375   -0.487722
376   -0.487722
377   -0.487722
378   -0.487722
Name:  ZN, Length: 379, dtype: float64

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train_boston_data,y_train_boston_data)
boston_data1 = np.loadtxt("Datasets/test.csv" , delimiter=',')
print(boston_data1)
print(boston_data1.shape)

[[ 2.91816626 -0.48772236  1.01599907 ...  0.80657583 -1.59755122
   1.04106182]
 [-0.40339151 -0.48772236  0.40609801 ... -1.13534664  0.44105193
  -0.89473812]
 [-0.4131781  -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.50084979]
 ...
 [-0.41001449  2.08745172 -1.37837329 ... -0.0719129   0.39094481
  -0.68167397]
 [-0.40317611 -0.48772236 -0.37597609 ...  1.13022958  0.34007019
   0.20142086]
 [-0.13356344 -0.48772236  1.2319449  ... -1.73641788 -2.93893082
   0.48877712]]
(127, 13)

In [19]:
y_predict = model.predict(boston_data1)
y_predict

C:\Users\RAKESH\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

array([-0.48770748, -0.48770748, -0.48770748,  0.41358972, -0.48770748,
       -0.48770748,  0.92852458, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
        1.01441571, -0.48769817, -0.48770748,  1.01441571, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748,  1.22902491,  2.51729265,
       -0.48770748, -0.48770748,  1.44361902, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748,  0.5852412 , -0.48770748,  0.41358972, -0.48770748,
       -0.48770748,  0.97163064,  2.51729265, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748,  3.37492862, -0.48770748,
       -0.48770748,  3.58946865, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748,  0.37067175, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748,  3.37491983,
       -0.48770748,  1.22902491,  0.37067175, -0.48770748,  2.94574728,
       -0.48770748, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748,  0.79982998, -0.48770748, -0.48770748, -0.48770748,
       -0.48769817, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748,  2.94574201, -0.48770748,  2.73127877,  1.7654915 ,
        0.37067175,  0.04875402,  0.37067175, -0.48770748, -0.48770748,
       -0.48770748,  0.04876333,  3.05297188,  0.5852412 , -0.48770748,
        1.87639101, -0.48770748, -0.48770748, -0.48770748, -0.48770748,
       -0.48770748, -0.48770748, -0.48770748,  0.04876333, -0.48770748,
       -0.48770748,  0.37067175, -0.48770748, -0.48770748,  2.08724706,
       -0.48770748, -0.48770748])

In [21]:
np.savetxt("Datasets/boston_predict.csv", y_predict)